# Generated by Django 3.0.4 on 2020-04-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='likedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalikes.profile')),
            ],
        ),
    ]
