# Generated by Django 3.0.4 on 2020-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0006_auto_20200517_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(default='some'),
        ),
    ]
