# Generated by Django 3.0.4 on 2020-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0007_userprofile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
