# Generated by Django 3.0.4 on 2020-05-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0016_auto_20200524_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likedby',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalikes.post'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
